### ISSUE TITLE
ability to specify a defined docfx.json

### ISSUE THREAD

**Issue by StephenHodgson** [CaseyHofland/docfx-unitypackage#2]
It'd be great to be able to specify a pre-defined docfx.json file to use when generating doc content

**Comment by CaseyHofland** [comment]
I've opted against this for the sake of staying accurate to the [DocTools](https://docs.unity3d.com/Packages/com.unity.package-manager-doctools@2.1/manual/developer-notes.html#pmdt). I want this tool to stay similar to Unity's documentation workflow so that, in case they ever release their tool, switching over is painless.

However, I do acknowledge that "removing one file" isn't exactly _painful_. I'm just anxious to do it as I'm still finding that line. Could you tell me what problem this functionality would solve for you?

**Comment by StephenHodgson** [comment]
I'd also like to add custom icons and other image assets as well.

**Comment by StephenHodgson** [comment]
Oh, I didn't know there was a useful package for this! thanks!

Is this link for DocTools in the main readme?

**Comment by StephenHodgson** [comment]
Is this link for DocTools in the main readme?

**Comment by CaseyHofland** [comment]
There is a link in the readme under "Usage". 

Do note that I am not affiliated with the DocTools. The DocTools are an internal Unity package that is not made openly accessible. docfx-unitypackage just uses the same workflow.
